#ifndef PARAMETERS_H
#define PARAMETERS_H

#define STEPS_OFFLINE 1000
#define STEPS_PER_REPETITION 5000
#define REPETITIONS_PER_GENERATION 2
#define QTY_NEST_BOXES 20
#define QTY_HIVES 10
#define QTY_BEES 100

#endif// PARAMETERS_H
